### ISSUE TITLE
[Feature Request] The @tailwindcss/custom-forms plugin is not compatible with Tailwind CSS v2.0.

### ISSUE THREAD

**Issue by Jinthebandit** [creativetimofficial/notus-svelte#3]
### What is your enhancement?
Migrate @tailwindcss/custom-forms to @tailwindcss/forms

[Tailwind CSS Upgrade Guide](https://tailwindcss.com/docs/upgrading-to-v2#update-typography-and-forms-plugins)

**Comment by EINazare** [comment]
Hello there, @Jinthebandit ,

We'll do it in about 2 months when we'll update this project.

Best,
Manu
