### ISSUE TITLE
[Bug] Typo on your landing page.

### ISSUE THREAD

**Issue by ulfaslak** [creativetimofficial/notus-svelte#6]
### Version
0.0
### Reproduction link
https://demos.creative-tim.com/notus-svelte/
### Operating System
OSX
### Device
amazing computer
### Browser & Version
super new and update
### Steps to reproduce
I love you product, but there's a typo on your landing page:

"It does not change or add any CSS to the already one from Tailwind CSS ."

Have a great day :)
### What is expected?
Eye pain
### What is actually happening?
Very eye pain

---

**Comment by EINazare** [comment]
Hello there, @ulfaslak ,

Thank you for your interest in working with our products.
Is this about the space before the dot - `.`? `CSS .` should be `CSS.`?

Best,
Manu

**Comment by ulfaslak** [comment]
It was the "to the already one" part that put me off :|. I'm guessing you wanted to write something like: "It does not change or add any CSS compared to vanilla Tailwind CSS."
